package com.xyinc.restapi.exception;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * Exception generated by the service api.
 * 
 * @author Felipe Cardoso
 *
 */
public class ServiceException extends WebApplicationException {

	private static final long serialVersionUID = -1968810582565223665L;
	private static final String MESSAGE = "An unexpected error was occurred.";

	public ServiceException() {
		super(Response.status(Status.INTERNAL_SERVER_ERROR).type(MediaType.APPLICATION_JSON)
		        .entity(new ServiceError(Status.INTERNAL_SERVER_ERROR.getStatusCode(), MESSAGE)).build());
	}
}
